// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCategories = `-- name: CreateCategories :one

INSERT INTO categories (
    id,
    name,
    type
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, type
`

type CreateCategoriesParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Type string    `json:"type"`
}

func (q *Queries) CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategories, arg.ID, arg.Name, arg.Type)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}
