// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   uuid.UUID   `json:"id"`
	Name string      `json:"name"`
	Type interface{} `json:"type"`
}

type Report struct {
	ID           uuid.UUID        `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Period       string           `json:"period"`
	TotalIncome  pgtype.Numeric   `json:"total_income"`
	TotalExpense pgtype.Numeric   `json:"total_expense"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type Transaction struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Amount      int64            `json:"amount"`
	Type        interface{}      `json:"type"`
	Description pgtype.Text      `json:"description"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID             int64            `json:"id"`
	Username       string           `json:"username"`
	FullName       string           `json:"full_name"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	UserUuid       uuid.UUID        `json:"user_uuid"`
}
