// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_reset_tokens (
    id,
    user_id,
    token,
    expired_at,
    is_used,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    FALSE,
    now()
) RETURNING id, user_id, token, is_used, expired_at, created_at, used_at
`

type CreatePasswordResetParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiredAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IsUsed,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, is_used, expired_at, created_at, used_at FROM password_reset_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IsUsed,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
UPDATE password_reset_tokens
SET is_used = TRUE,
    used_at = now()
WHERE id = $1
`

func (q *Queries) UsePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, id)
	return err
}
