// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateReportUser(ctx context.Context, arg CreateReportUserParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDetailsReportbyUser(ctx context.Context, userID uuid.UUID) ([]GetDetailsReportbyUserRow, error)
	GetReportbyCategory(ctx context.Context) ([]GetReportbyCategoryRow, error)
	GetReportbyDate(ctx context.Context, arg GetReportbyDateParams) ([]GetReportbyDateRow, error)
	GetReportbyUser(ctx context.Context, userID uuid.UUID) (GetReportbyUserRow, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
