// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateMonthlyReport(ctx context.Context, userID uuid.UUID) error
	CreateReportUser(ctx context.Context, arg CreateReportUserParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetCategoryById(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetDetailsReportByUser(ctx context.Context, userID uuid.UUID) ([]GetDetailsReportByUserRow, error)
	GetReportByCategory(ctx context.Context) ([]GetReportByCategoryRow, error)
	GetReportByDate(ctx context.Context, arg GetReportByDateParams) ([]GetReportByDateRow, error)
	GetReportByUser(ctx context.Context, userID uuid.UUID) (GetReportByUserRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionByType(ctx context.Context, arg GetTransactionByTypeParams) ([]Transaction, error)
	GetTransactionByuserId(ctx context.Context, userID uuid.UUID) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
