// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    username,
    full_name,
    email,
    hashed_password,
    user_uuid   
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at
`

type CreateUserParams struct {
	Username       string    `json:"username"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	UserUuid       uuid.UUID `json:"user_uuid"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
		arg.UserUuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at FROM users 
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at FROM users 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByUserId = `-- name: GetUserByUserId :one
SELECT id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at FROM users 
WHERE user_uuid = $1
`

func (q *Queries) GetUserByUserId(ctx context.Context, userUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserId, userUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at FROM users 
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    hashed_password = COALESCE($1, hashed_password),
    updated_at = COALESCE($2, updated_at),
    full_name = COALESCE($3, full_name),
    email = COALESCE($4, email),
    is_email_verified = COALESCE($5, is_email_verified)
WHERE
    username = $6 OR user_uuid = $7
RETURNING id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at
`

type UpdateUserParams struct {
	HashedPassword  pgtype.Text        `json:"hashed_password"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FullName        pgtype.Text        `json:"full_name"`
	Email           pgtype.Text        `json:"email"`
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	Username        string             `json:"username"`
	UserUuid        uuid.UUID          `json:"user_uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.HashedPassword,
		arg.UpdatedAt,
		arg.FullName,
		arg.Email,
		arg.IsEmailVerified,
		arg.Username,
		arg.UserUuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET 
    hashed_password = $2,
    password_changed_at = now(),
    updated_at = now()
WHERE user_uuid = $1
RETURNING id, username, full_name, email, hashed_password, role, created_at, updated_at, deleted_at, user_uuid, is_email_verified, password_changed_at
`

type UpdateUserPasswordParams struct {
	UserUuid       uuid.UUID `json:"user_uuid"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.UserUuid, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserUuid,
		&i.IsEmailVerified,
		&i.PasswordChangedAt,
	)
	return i, err
}

const verifiedEmail = `-- name: VerifiedEmail :one
SELECT is_email_verified FROM users
WHERE user_uuid = $1
LIMIT 1
`

func (q *Queries) VerifiedEmail(ctx context.Context, userUuid uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, verifiedEmail, userUuid)
	var is_email_verified bool
	err := row.Scan(&is_email_verified)
	return is_email_verified, err
}
