// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: verify_emails.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVerifyEmails = `-- name: CreateVerifyEmails :one
INSERT INTO verify_emails (
    user_id,
    email,
    secret_code
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, user_id, email, secret_code, is_used, created_at, expires_at
`

type CreateVerifyEmailsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
}

func (q *Queries) CreateVerifyEmails(ctx context.Context, arg CreateVerifyEmailsParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, createVerifyEmails, arg.UserID, arg.Email, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateVerifyEmails = `-- name: UpdateVerifyEmails :one
UPDATE verify_emails
SET
    is_used = true
WHERE
    id = $1
    AND secret_code = $2
    AND is_used = false
    AND expires_at > now()
RETURNING id, user_id, email, secret_code, is_used, created_at, expires_at
`

type UpdateVerifyEmailsParams struct {
	ID         int64  `json:"id"`
	SecretCode string `json:"secret_code"`
}

func (q *Queries) UpdateVerifyEmails(ctx context.Context, arg UpdateVerifyEmailsParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, updateVerifyEmails, arg.ID, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
