// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_update_transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *int64                 `protobuf:"varint,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	CategoryId    *string                `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_rpc_update_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() int64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTransactionRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateTransactionRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_rpc_update_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_rpc_update_transaction_proto protoreflect.FileDescriptor

const file_rpc_update_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_update_transaction.proto\x12\x02pb\x1a\x11transaction.proto\"\xfa\x01\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\x03H\x00R\x06amount\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x02R\x04type\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x05 \x01(\tH\x03R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userIdB\t\n" +
	"\a_amountB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_category_id\"N\n" +
	"\x19UpdateTransactionResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransactionB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_update_transaction_proto_rawDescOnce sync.Once
	file_rpc_update_transaction_proto_rawDescData []byte
)

func file_rpc_update_transaction_proto_rawDescGZIP() []byte {
	file_rpc_update_transaction_proto_rawDescOnce.Do(func() {
		file_rpc_update_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_transaction_proto_rawDesc), len(file_rpc_update_transaction_proto_rawDesc)))
	})
	return file_rpc_update_transaction_proto_rawDescData
}

var file_rpc_update_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_transaction_proto_goTypes = []any{
	(*UpdateTransactionRequest)(nil),  // 0: pb.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil), // 1: pb.UpdateTransactionResponse
	(*Transaction)(nil),               // 2: pb.Transaction
}
var file_rpc_update_transaction_proto_depIdxs = []int32{
	2, // 0: pb.UpdateTransactionResponse.transaction:type_name -> pb.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_transaction_proto_init() }
func file_rpc_update_transaction_proto_init() {
	if File_rpc_update_transaction_proto != nil {
		return
	}
	file_transaction_proto_init()
	file_rpc_update_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_transaction_proto_rawDesc), len(file_rpc_update_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_transaction_proto_goTypes,
		DependencyIndexes: file_rpc_update_transaction_proto_depIdxs,
		MessageInfos:      file_rpc_update_transaction_proto_msgTypes,
	}.Build()
	File_rpc_update_transaction_proto = out.File
	file_rpc_update_transaction_proto_goTypes = nil
	file_rpc_update_transaction_proto_depIdxs = nil
}
