// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_get_transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_rpc_get_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_transaction_proto_rawDescGZIP(), []int{0}
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   []*Transaction         `protobuf:"bytes,1,rep,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_rpc_get_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionResponse) GetTransaction() []*Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_rpc_get_transaction_proto protoreflect.FileDescriptor

const file_rpc_get_transaction_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_get_transaction.proto\x12\x02pb\x1a\x11transaction.proto\"\x17\n" +
	"\x15GetTransactionRequest\"K\n" +
	"\x16GetTransactionResponse\x121\n" +
	"\vtransaction\x18\x01 \x03(\v2\x0f.pb.TransactionR\vtransactionB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_get_transaction_proto_rawDescOnce sync.Once
	file_rpc_get_transaction_proto_rawDescData []byte
)

func file_rpc_get_transaction_proto_rawDescGZIP() []byte {
	file_rpc_get_transaction_proto_rawDescOnce.Do(func() {
		file_rpc_get_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_transaction_proto_rawDesc), len(file_rpc_get_transaction_proto_rawDesc)))
	})
	return file_rpc_get_transaction_proto_rawDescData
}

var file_rpc_get_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_transaction_proto_goTypes = []any{
	(*GetTransactionRequest)(nil),  // 0: pb.GetTransactionRequest
	(*GetTransactionResponse)(nil), // 1: pb.GetTransactionResponse
	(*Transaction)(nil),            // 2: pb.Transaction
}
var file_rpc_get_transaction_proto_depIdxs = []int32{
	2, // 0: pb.GetTransactionResponse.transaction:type_name -> pb.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_transaction_proto_init() }
func file_rpc_get_transaction_proto_init() {
	if File_rpc_get_transaction_proto != nil {
		return
	}
	file_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_transaction_proto_rawDesc), len(file_rpc_get_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_transaction_proto_goTypes,
		DependencyIndexes: file_rpc_get_transaction_proto_depIdxs,
		MessageInfos:      file_rpc_get_transaction_proto_msgTypes,
	}.Build()
	File_rpc_get_transaction_proto = out.File
	file_rpc_get_transaction_proto_goTypes = nil
	file_rpc_get_transaction_proto_depIdxs = nil
}
