// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_create_categories.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoriesRequest) Reset() {
	*x = CreateCategoriesRequest{}
	mi := &file_rpc_create_categories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoriesRequest) ProtoMessage() {}

func (x *CreateCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_categories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoriesRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_categories_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoriesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoriesResponse) Reset() {
	*x = CreateCategoriesResponse{}
	mi := &file_rpc_create_categories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoriesResponse) ProtoMessage() {}

func (x *CreateCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_categories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoriesResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_categories_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoriesResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_rpc_create_categories_proto protoreflect.FileDescriptor

const file_rpc_create_categories_proto_rawDesc = "" +
	"\n" +
	"\x1brpc_create_categories.proto\x12\x02pb\x1a\x10categories.proto\"-\n" +
	"\x17CreateCategoriesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x18CreateCategoriesResponse\x12(\n" +
	"\bcategory\x18\x01 \x01(\v2\f.pb.CategoryR\bcategoryB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_create_categories_proto_rawDescOnce sync.Once
	file_rpc_create_categories_proto_rawDescData []byte
)

func file_rpc_create_categories_proto_rawDescGZIP() []byte {
	file_rpc_create_categories_proto_rawDescOnce.Do(func() {
		file_rpc_create_categories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_categories_proto_rawDesc), len(file_rpc_create_categories_proto_rawDesc)))
	})
	return file_rpc_create_categories_proto_rawDescData
}

var file_rpc_create_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_categories_proto_goTypes = []any{
	(*CreateCategoriesRequest)(nil),  // 0: pb.CreateCategoriesRequest
	(*CreateCategoriesResponse)(nil), // 1: pb.CreateCategoriesResponse
	(*Category)(nil),                 // 2: pb.Category
}
var file_rpc_create_categories_proto_depIdxs = []int32{
	2, // 0: pb.CreateCategoriesResponse.category:type_name -> pb.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_categories_proto_init() }
func file_rpc_create_categories_proto_init() {
	if File_rpc_create_categories_proto != nil {
		return
	}
	file_categories_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_categories_proto_rawDesc), len(file_rpc_create_categories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_categories_proto_goTypes,
		DependencyIndexes: file_rpc_create_categories_proto_depIdxs,
		MessageInfos:      file_rpc_create_categories_proto_msgTypes,
	}.Build()
	File_rpc_create_categories_proto = out.File
	file_rpc_create_categories_proto_goTypes = nil
	file_rpc_create_categories_proto_depIdxs = nil
}
