// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_create_transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_rpc_create_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateTransactionRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Category      *Category              `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_rpc_create_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreateTransactionResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_rpc_create_transaction_proto protoreflect.FileDescriptor

const file_rpc_create_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1crpc_create_transaction.proto\x12\x02pb\x1a\x11transaction.proto\x1a\x10categories.proto\"\xc7\x01\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\"x\n" +
	"\x19CreateTransactionResponse\x121\n" +
	"\vtransaction\x18\x01 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12(\n" +
	"\bcategory\x18\x02 \x01(\v2\f.pb.CategoryR\bcategoryB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_create_transaction_proto_rawDescOnce sync.Once
	file_rpc_create_transaction_proto_rawDescData []byte
)

func file_rpc_create_transaction_proto_rawDescGZIP() []byte {
	file_rpc_create_transaction_proto_rawDescOnce.Do(func() {
		file_rpc_create_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_transaction_proto_rawDesc), len(file_rpc_create_transaction_proto_rawDesc)))
	})
	return file_rpc_create_transaction_proto_rawDescData
}

var file_rpc_create_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: pb.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 1: pb.CreateTransactionResponse
	(*Transaction)(nil),               // 2: pb.Transaction
	(*Category)(nil),                  // 3: pb.Category
}
var file_rpc_create_transaction_proto_depIdxs = []int32{
	2, // 0: pb.CreateTransactionResponse.transaction:type_name -> pb.Transaction
	3, // 1: pb.CreateTransactionResponse.category:type_name -> pb.Category
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_transaction_proto_init() }
func file_rpc_create_transaction_proto_init() {
	if File_rpc_create_transaction_proto != nil {
		return
	}
	file_transaction_proto_init()
	file_categories_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_transaction_proto_rawDesc), len(file_rpc_create_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_transaction_proto_goTypes,
		DependencyIndexes: file_rpc_create_transaction_proto_depIdxs,
		MessageInfos:      file_rpc_create_transaction_proto_msgTypes,
	}.Build()
	File_rpc_create_transaction_proto = out.File
	file_rpc_create_transaction_proto_goTypes = nil
	file_rpc_create_transaction_proto_depIdxs = nil
}
