// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_get_report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReportByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByUserRequest) Reset() {
	*x = GetReportByUserRequest{}
	mi := &file_rpc_get_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByUserRequest) ProtoMessage() {}

func (x *GetReportByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByUserRequest.ProtoReflect.Descriptor instead.
func (*GetReportByUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{0}
}

func (x *GetReportByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetReportByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,2,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,3,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByUserResponse) Reset() {
	*x = GetReportByUserResponse{}
	mi := &file_rpc_get_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByUserResponse) ProtoMessage() {}

func (x *GetReportByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByUserResponse.ProtoReflect.Descriptor instead.
func (*GetReportByUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{1}
}

func (x *GetReportByUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReportByUserResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *GetReportByUserResponse) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

type GetDetailsReportByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsReportByUserRequest) Reset() {
	*x = GetDetailsReportByUserRequest{}
	mi := &file_rpc_get_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsReportByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsReportByUserRequest) ProtoMessage() {}

func (x *GetDetailsReportByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsReportByUserRequest.ProtoReflect.Descriptor instead.
func (*GetDetailsReportByUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{2}
}

func (x *GetDetailsReportByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDetailsReportByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsReportByUserResponse) Reset() {
	*x = GetDetailsReportByUserResponse{}
	mi := &file_rpc_get_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsReportByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsReportByUserResponse) ProtoMessage() {}

func (x *GetDetailsReportByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsReportByUserResponse.ProtoReflect.Descriptor instead.
func (*GetDetailsReportByUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetDetailsReportByUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDetailsReportByUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDetailsReportByUserResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetDetailsReportByUserResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetDetailsReportByUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetReportByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByDateRequest) Reset() {
	*x = GetReportByDateRequest{}
	mi := &file_rpc_get_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByDateRequest) ProtoMessage() {}

func (x *GetReportByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByDateRequest.ProtoReflect.Descriptor instead.
func (*GetReportByDateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{4}
}

func (x *GetReportByDateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReportByDateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetReportByDateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ReportByDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportByDate) Reset() {
	*x = ReportByDate{}
	mi := &file_rpc_get_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportByDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportByDate) ProtoMessage() {}

func (x *ReportByDate) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportByDate.ProtoReflect.Descriptor instead.
func (*ReportByDate) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{5}
}

func (x *ReportByDate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportByDate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReportByDate) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReportByDate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReportByDate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportByDate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetReportByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportByDate        `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByDateResponse) Reset() {
	*x = GetReportByDateResponse{}
	mi := &file_rpc_get_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByDateResponse) ProtoMessage() {}

func (x *GetReportByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByDateResponse.ProtoReflect.Descriptor instead.
func (*GetReportByDateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{6}
}

func (x *GetReportByDateResponse) GetReports() []*ReportByDate {
	if x != nil {
		return x.Reports
	}
	return nil
}

type GetReportByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByCategoryRequest) Reset() {
	*x = GetReportByCategoryRequest{}
	mi := &file_rpc_get_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByCategoryRequest) ProtoMessage() {}

func (x *GetReportByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetReportByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{7}
}

type GetReportByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,2,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,3,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportByCategoryResponse) Reset() {
	*x = GetReportByCategoryResponse{}
	mi := &file_rpc_get_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportByCategoryResponse) ProtoMessage() {}

func (x *GetReportByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetReportByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_report_proto_rawDescGZIP(), []int{8}
}

func (x *GetReportByCategoryResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetReportByCategoryResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *GetReportByCategoryResponse) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

var File_rpc_get_report_proto protoreflect.FileDescriptor

const file_rpc_get_report_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_get_report.proto\x12\x02pb\x1a\freport.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n" +
	"\x16GetReportByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"z\n" +
	"\x17GetReportByUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_income\x18\x02 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x03 \x01(\x01R\ftotalExpense\"8\n" +
	"\x1dGetDetailsReportByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa2\x01\n" +
	"\x1eGetDetailsReportByUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"k\n" +
	"\x16GetReportByDateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xc0\x01\n" +
	"\fReportByDate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"E\n" +
	"\x17GetReportByDateResponse\x12*\n" +
	"\areports\x18\x01 \x03(\v2\x10.pb.ReportByDateR\areports\"\x1c\n" +
	"\x1aGetReportByCategoryRequest\"\x86\x01\n" +
	"\x1bGetReportByCategoryResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12!\n" +
	"\ftotal_income\x18\x02 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x03 \x01(\x01R\ftotalExpenseB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_get_report_proto_rawDescOnce sync.Once
	file_rpc_get_report_proto_rawDescData []byte
)

func file_rpc_get_report_proto_rawDescGZIP() []byte {
	file_rpc_get_report_proto_rawDescOnce.Do(func() {
		file_rpc_get_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_report_proto_rawDesc), len(file_rpc_get_report_proto_rawDesc)))
	})
	return file_rpc_get_report_proto_rawDescData
}

var file_rpc_get_report_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_get_report_proto_goTypes = []any{
	(*GetReportByUserRequest)(nil),         // 0: pb.GetReportByUserRequest
	(*GetReportByUserResponse)(nil),        // 1: pb.GetReportByUserResponse
	(*GetDetailsReportByUserRequest)(nil),  // 2: pb.GetDetailsReportByUserRequest
	(*GetDetailsReportByUserResponse)(nil), // 3: pb.GetDetailsReportByUserResponse
	(*GetReportByDateRequest)(nil),         // 4: pb.GetReportByDateRequest
	(*ReportByDate)(nil),                   // 5: pb.ReportByDate
	(*GetReportByDateResponse)(nil),        // 6: pb.GetReportByDateResponse
	(*GetReportByCategoryRequest)(nil),     // 7: pb.GetReportByCategoryRequest
	(*GetReportByCategoryResponse)(nil),    // 8: pb.GetReportByCategoryResponse
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_rpc_get_report_proto_depIdxs = []int32{
	9, // 0: pb.ReportByDate.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: pb.GetReportByDateResponse.reports:type_name -> pb.ReportByDate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_get_report_proto_init() }
func file_rpc_get_report_proto_init() {
	if File_rpc_get_report_proto != nil {
		return
	}
	file_report_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_report_proto_rawDesc), len(file_rpc_get_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_report_proto_goTypes,
		DependencyIndexes: file_rpc_get_report_proto_depIdxs,
		MessageInfos:      file_rpc_get_report_proto_msgTypes,
	}.Build()
	File_rpc_get_report_proto = out.File
	file_rpc_get_report_proto_goTypes = nil
	file_rpc_get_report_proto_depIdxs = nil
}
