// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: rpc_get_categories.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_rpc_get_categories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_categories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_categories_proto_rawDescGZIP(), []int{0}
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_rpc_get_categories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_categories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_categories_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_rpc_get_categories_proto protoreflect.FileDescriptor

const file_rpc_get_categories_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_get_categories.proto\x12\x02pb\x1a\x10categories.proto\"\x16\n" +
	"\x14GetCategoriesRequest\"E\n" +
	"\x15GetCategoriesResponse\x12,\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\f.pb.CategoryR\n" +
	"categoriesB&Z$github.com/gufir/money-management/pbb\x06proto3"

var (
	file_rpc_get_categories_proto_rawDescOnce sync.Once
	file_rpc_get_categories_proto_rawDescData []byte
)

func file_rpc_get_categories_proto_rawDescGZIP() []byte {
	file_rpc_get_categories_proto_rawDescOnce.Do(func() {
		file_rpc_get_categories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_categories_proto_rawDesc), len(file_rpc_get_categories_proto_rawDesc)))
	})
	return file_rpc_get_categories_proto_rawDescData
}

var file_rpc_get_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_categories_proto_goTypes = []any{
	(*GetCategoriesRequest)(nil),  // 0: pb.GetCategoriesRequest
	(*GetCategoriesResponse)(nil), // 1: pb.GetCategoriesResponse
	(*Category)(nil),              // 2: pb.Category
}
var file_rpc_get_categories_proto_depIdxs = []int32{
	2, // 0: pb.GetCategoriesResponse.categories:type_name -> pb.Category
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_categories_proto_init() }
func file_rpc_get_categories_proto_init() {
	if File_rpc_get_categories_proto != nil {
		return
	}
	file_categories_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_categories_proto_rawDesc), len(file_rpc_get_categories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_categories_proto_goTypes,
		DependencyIndexes: file_rpc_get_categories_proto_depIdxs,
		MessageInfos:      file_rpc_get_categories_proto_msgTypes,
	}.Build()
	File_rpc_get_categories_proto = out.File
	file_rpc_get_categories_proto_goTypes = nil
	file_rpc_get_categories_proto_depIdxs = nil
}
