// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service_money_management.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoneyManagement_CreateUser_FullMethodName             = "/pb.MoneyManagement/CreateUser"
	MoneyManagement_UpdateUser_FullMethodName             = "/pb.MoneyManagement/UpdateUser"
	MoneyManagement_LoginUser_FullMethodName              = "/pb.MoneyManagement/LoginUser"
	MoneyManagement_CreateTransaction_FullMethodName      = "/pb.MoneyManagement/CreateTransaction"
	MoneyManagement_UpdateTransaction_FullMethodName      = "/pb.MoneyManagement/UpdateTransaction"
	MoneyManagement_CreateCategories_FullMethodName       = "/pb.MoneyManagement/CreateCategories"
	MoneyManagement_UpdateCategories_FullMethodName       = "/pb.MoneyManagement/UpdateCategories"
	MoneyManagement_GetCategories_FullMethodName          = "/pb.MoneyManagement/GetCategories"
	MoneyManagement_GetTransaction_FullMethodName         = "/pb.MoneyManagement/GetTransaction"
	MoneyManagement_GetUser_FullMethodName                = "/pb.MoneyManagement/GetUser"
	MoneyManagement_CreateReport_FullMethodName           = "/pb.MoneyManagement/CreateReport"
	MoneyManagement_CreateMonthlyReport_FullMethodName    = "/pb.MoneyManagement/CreateMonthlyReport"
	MoneyManagement_GetReportByUser_FullMethodName        = "/pb.MoneyManagement/GetReportByUser"
	MoneyManagement_GetDetailsReportByUser_FullMethodName = "/pb.MoneyManagement/GetDetailsReportByUser"
	MoneyManagement_GetReportByDate_FullMethodName        = "/pb.MoneyManagement/GetReportByDate"
	MoneyManagement_GetReportByCategory_FullMethodName    = "/pb.MoneyManagement/GetReportByCategory"
	MoneyManagement_VerifyEmail_FullMethodName            = "/pb.MoneyManagement/VerifyEmail"
	MoneyManagement_ForgotPassword_FullMethodName         = "/pb.MoneyManagement/ForgotPassword"
	MoneyManagement_ResetPassword_FullMethodName          = "/pb.MoneyManagement/ResetPassword"
)

// MoneyManagementClient is the client API for MoneyManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for SimpleBank
type MoneyManagementClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*UpdateTransactionResponse, error)
	CreateCategories(ctx context.Context, in *CreateCategoriesRequest, opts ...grpc.CallOption) (*CreateCategoriesResponse, error)
	UpdateCategories(ctx context.Context, in *UpdateCategoriesRequest, opts ...grpc.CallOption) (*UpdateCategoriesResponse, error)
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error)
	CreateMonthlyReport(ctx context.Context, in *CreateMonthlyReportRequest, opts ...grpc.CallOption) (*CreateMonthlyReportResponse, error)
	GetReportByUser(ctx context.Context, in *GetReportByUserRequest, opts ...grpc.CallOption) (*GetReportByUserResponse, error)
	GetDetailsReportByUser(ctx context.Context, in *GetDetailsReportByUserRequest, opts ...grpc.CallOption) (*GetDetailsReportByUserResponse, error)
	GetReportByDate(ctx context.Context, in *GetReportByDateRequest, opts ...grpc.CallOption) (*GetReportByDateResponse, error)
	GetReportByCategory(ctx context.Context, in *GetReportByCategoryRequest, opts ...grpc.CallOption) (*GetReportByCategoryResponse, error)
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
}

type moneyManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyManagementClient(cc grpc.ClientConnInterface) MoneyManagementClient {
	return &moneyManagementClient{cc}
}

func (c *moneyManagementClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_CreateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) UpdateTransaction(ctx context.Context, in *UpdateTransactionRequest, opts ...grpc.CallOption) (*UpdateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTransactionResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_UpdateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) CreateCategories(ctx context.Context, in *CreateCategoriesRequest, opts ...grpc.CallOption) (*CreateCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoriesResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_CreateCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) UpdateCategories(ctx context.Context, in *UpdateCategoriesRequest, opts ...grpc.CallOption) (*UpdateCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoriesResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_UpdateCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReportResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) CreateMonthlyReport(ctx context.Context, in *CreateMonthlyReportRequest, opts ...grpc.CallOption) (*CreateMonthlyReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMonthlyReportResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_CreateMonthlyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetReportByUser(ctx context.Context, in *GetReportByUserRequest, opts ...grpc.CallOption) (*GetReportByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportByUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetReportByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetDetailsReportByUser(ctx context.Context, in *GetDetailsReportByUserRequest, opts ...grpc.CallOption) (*GetDetailsReportByUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailsReportByUserResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetDetailsReportByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetReportByDate(ctx context.Context, in *GetReportByDateRequest, opts ...grpc.CallOption) (*GetReportByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportByDateResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetReportByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) GetReportByCategory(ctx context.Context, in *GetReportByCategoryRequest, opts ...grpc.CallOption) (*GetReportByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReportByCategoryResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_GetReportByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_ForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyManagementClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, MoneyManagement_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyManagementServer is the server API for MoneyManagement service.
// All implementations must embed UnimplementedMoneyManagementServer
// for forward compatibility.
//
// Service definition for SimpleBank
type MoneyManagementServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	UpdateTransaction(context.Context, *UpdateTransactionRequest) (*UpdateTransactionResponse, error)
	CreateCategories(context.Context, *CreateCategoriesRequest) (*CreateCategoriesResponse, error)
	UpdateCategories(context.Context, *UpdateCategoriesRequest) (*UpdateCategoriesResponse, error)
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error)
	CreateMonthlyReport(context.Context, *CreateMonthlyReportRequest) (*CreateMonthlyReportResponse, error)
	GetReportByUser(context.Context, *GetReportByUserRequest) (*GetReportByUserResponse, error)
	GetDetailsReportByUser(context.Context, *GetDetailsReportByUserRequest) (*GetDetailsReportByUserResponse, error)
	GetReportByDate(context.Context, *GetReportByDateRequest) (*GetReportByDateResponse, error)
	GetReportByCategory(context.Context, *GetReportByCategoryRequest) (*GetReportByCategoryResponse, error)
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	mustEmbedUnimplementedMoneyManagementServer()
}

// UnimplementedMoneyManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoneyManagementServer struct{}

func (UnimplementedMoneyManagementServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMoneyManagementServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedMoneyManagementServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedMoneyManagementServer) CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (UnimplementedMoneyManagementServer) UpdateTransaction(context.Context, *UpdateTransactionRequest) (*UpdateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransaction not implemented")
}
func (UnimplementedMoneyManagementServer) CreateCategories(context.Context, *CreateCategoriesRequest) (*CreateCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategories not implemented")
}
func (UnimplementedMoneyManagementServer) UpdateCategories(context.Context, *UpdateCategoriesRequest) (*UpdateCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategories not implemented")
}
func (UnimplementedMoneyManagementServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedMoneyManagementServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedMoneyManagementServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedMoneyManagementServer) CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedMoneyManagementServer) CreateMonthlyReport(context.Context, *CreateMonthlyReportRequest) (*CreateMonthlyReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMonthlyReport not implemented")
}
func (UnimplementedMoneyManagementServer) GetReportByUser(context.Context, *GetReportByUserRequest) (*GetReportByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportByUser not implemented")
}
func (UnimplementedMoneyManagementServer) GetDetailsReportByUser(context.Context, *GetDetailsReportByUserRequest) (*GetDetailsReportByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailsReportByUser not implemented")
}
func (UnimplementedMoneyManagementServer) GetReportByDate(context.Context, *GetReportByDateRequest) (*GetReportByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportByDate not implemented")
}
func (UnimplementedMoneyManagementServer) GetReportByCategory(context.Context, *GetReportByCategoryRequest) (*GetReportByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportByCategory not implemented")
}
func (UnimplementedMoneyManagementServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedMoneyManagementServer) ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedMoneyManagementServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedMoneyManagementServer) mustEmbedUnimplementedMoneyManagementServer() {}
func (UnimplementedMoneyManagementServer) testEmbeddedByValue()                         {}

// UnsafeMoneyManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneyManagementServer will
// result in compilation errors.
type UnsafeMoneyManagementServer interface {
	mustEmbedUnimplementedMoneyManagementServer()
}

func RegisterMoneyManagementServer(s grpc.ServiceRegistrar, srv MoneyManagementServer) {
	// If the following call pancis, it indicates UnimplementedMoneyManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoneyManagement_ServiceDesc, srv)
}

func _MoneyManagement_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_CreateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_UpdateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).UpdateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_UpdateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).UpdateTransaction(ctx, req.(*UpdateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_CreateCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).CreateCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_CreateCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).CreateCategories(ctx, req.(*CreateCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_UpdateCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).UpdateCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_UpdateCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).UpdateCategories(ctx, req.(*UpdateCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_CreateMonthlyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMonthlyReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).CreateMonthlyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_CreateMonthlyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).CreateMonthlyReport(ctx, req.(*CreateMonthlyReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetReportByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetReportByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetReportByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetReportByUser(ctx, req.(*GetReportByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetDetailsReportByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailsReportByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetDetailsReportByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetDetailsReportByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetDetailsReportByUser(ctx, req.(*GetDetailsReportByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetReportByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetReportByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetReportByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetReportByDate(ctx, req.(*GetReportByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_GetReportByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).GetReportByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_GetReportByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).GetReportByCategory(ctx, req.(*GetReportByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_ForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyManagement_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyManagementServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyManagement_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyManagementServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoneyManagement_ServiceDesc is the grpc.ServiceDesc for MoneyManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoneyManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MoneyManagement",
	HandlerType: (*MoneyManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MoneyManagement_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _MoneyManagement_UpdateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _MoneyManagement_LoginUser_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _MoneyManagement_CreateTransaction_Handler,
		},
		{
			MethodName: "UpdateTransaction",
			Handler:    _MoneyManagement_UpdateTransaction_Handler,
		},
		{
			MethodName: "CreateCategories",
			Handler:    _MoneyManagement_CreateCategories_Handler,
		},
		{
			MethodName: "UpdateCategories",
			Handler:    _MoneyManagement_UpdateCategories_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _MoneyManagement_GetCategories_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _MoneyManagement_GetTransaction_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MoneyManagement_GetUser_Handler,
		},
		{
			MethodName: "CreateReport",
			Handler:    _MoneyManagement_CreateReport_Handler,
		},
		{
			MethodName: "CreateMonthlyReport",
			Handler:    _MoneyManagement_CreateMonthlyReport_Handler,
		},
		{
			MethodName: "GetReportByUser",
			Handler:    _MoneyManagement_GetReportByUser_Handler,
		},
		{
			MethodName: "GetDetailsReportByUser",
			Handler:    _MoneyManagement_GetDetailsReportByUser_Handler,
		},
		{
			MethodName: "GetReportByDate",
			Handler:    _MoneyManagement_GetReportByDate_Handler,
		},
		{
			MethodName: "GetReportByCategory",
			Handler:    _MoneyManagement_GetReportByCategory_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _MoneyManagement_VerifyEmail_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _MoneyManagement_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _MoneyManagement_ResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_money_management.proto",
}
