// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: service_money_management.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_money_management_proto protoreflect.FileDescriptor

const file_service_money_management_proto_rawDesc = "" +
	"\n" +
	"\x1eservice_money_management.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1crpc_create_transaction.proto\x1a\x1crpc_update_transaction.proto\x1a\x1brpc_create_categories.proto\x1a\x1brpc_update_categories.proto\x1a\x18rpc_get_categories.proto\x1a\x19rpc_get_transaction.proto\x1a\x12rpc_get_user.proto\x1a\x17rpc_create_report.proto\x1a\x1frpc_create_monthly_report.proto\x1a\x14rpc_get_report.proto\x1a\x16rpc_verify_email.proto\x1a\x19rpc_forgot_password.proto2\xed\x18\n" +
	"\x0fMoneyManagement\x12\x91\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"T\x92A7\x12\x11Create a new user\x1a\"Use this API to create a new user.\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\x85\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"H\x92A+\x12\vUpdate user\x1a\x1cUse this API to update user.\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/update_user\x12\xa4\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"j\x92AN\x12\n" +
	"Login user\x1a@Use this API to login user and get access token & refresh token.\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\xbb\x01\n" +
	"\x11CreateTransaction\x12\x1c.pb.CreateTransactionRequest\x1a\x1d.pb.CreateTransactionResponse\"i\x92AE\x12\x18Create a new transaction\x1a)Use this API to create a new transaction.\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/create_transaction\x12\xaf\x01\n" +
	"\x11UpdateTransaction\x12\x1c.pb.UpdateTransactionRequest\x1a\x1d.pb.UpdateTransactionResponse\"]\x92A9\x12\x12Update transaction\x1a#Use this API to update transaction.\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/update_transaction\x12\xb1\x01\n" +
	"\x10CreateCategories\x12\x1b.pb.CreateCategoriesRequest\x1a\x1c.pb.CreateCategoriesResponse\"b\x92A?\x12\x15Create a new category\x1a&Use this API to create a new category.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/create_categories\x12\xa5\x01\n" +
	"\x10UpdateCategories\x12\x1b.pb.UpdateCategoriesRequest\x1a\x1c.pb.UpdateCategoriesResponse\"V\x92A3\x12\x0fUpdate category\x1a Use this API to update category.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/update_categories\x12\x9c\x01\n" +
	"\rGetCategories\x12\x18.pb.GetCategoriesRequest\x1a\x19.pb.GetCategoriesResponse\"V\x92A9\x12\x12Get all categories\x1a#Use this API to get all categories.\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/get_categories\x12\x99\x01\n" +
	"\x0eGetTransaction\x12\x19.pb.GetTransactionRequest\x1a\x1a.pb.GetTransactionResponse\"P\x92A2\x12\x0fGet transaction\x1a\x1fUse this API to get transaction\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/get_transaction\x12t\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse\"@\x92A)\x12\bGet User\x1a\x1dUse this API to get User Data\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/get_user\x12\x92\x01\n" +
	"\fCreateReport\x12\x17.pb.CreateReportRequest\x1a\x18.pb.CreateReportResponse\"O\x92A0\x12\rCreate Report\x1a\x1fUse this API to create a Report\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/create_report\x12\xbf\x01\n" +
	"\x13CreateMonthlyReport\x12\x1e.pb.CreateMonthlyReportRequest\x1a\x1f.pb.CreateMonthlyReportResponse\"g\x92A@\x12\x15Create Monthly Report\x1a'Use this API to create a Monthly Report\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/create_monthly_report\x12\xa5\x01\n" +
	"\x0fGetReportByUser\x12\x1a.pb.GetReportByUserRequest\x1a\x1b.pb.GetReportByUserResponse\"Y\x92A8\x12\x12Get Report by User\x1a\"Use this API to Get Report by User\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/get_report_by_user\x12\xd2\x01\n" +
	"\x16GetDetailsReportByUser\x12!.pb.GetDetailsReportByUserRequest\x1a\".pb.GetDetailsReportByUserResponse\"q\x92AH\x12\x1aGet Report Details by User\x1a*Use this API to Get Details Report by User\x82\xd3\xe4\x93\x02 \x12\x1e/v1/get_details_report_by_user\x12\xad\x01\n" +
	"\x0fGetReportByDate\x12\x1a.pb.GetReportByDateRequest\x1a\x1b.pb.GetReportByDateResponse\"a\x92A@\x12\x1aGet Report Details by Date\x1a\"Use this API to Get Report by Date\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/get_report_by_date\x12\xbd\x01\n" +
	"\x13GetReportByCategory\x12\x1e.pb.GetReportByCategoryRequest\x1a\x1f.pb.GetReportByCategoryResponse\"e\x92A@\x12\x16Get Report by Category\x1a&Use this API to Get Report by Category\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/get_report_by_category\x12\x8d\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"M\x92A2\x12\fVerify Email\x1a\"Use this API to verify user email.\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12\xa7\x01\n" +
	"\x0eForgotPassword\x12\x19.pb.ForgotPasswordRequest\x1a\x1a.pb.ForgotPasswordResponse\"^\x92A=\x12\x0fForgot Password\x1a*Use this API to initiate a password reset.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/forgot_password\x12\x9b\x01\n" +
	"\rResetPassword\x12\x18.pb.ResetPasswordRequest\x1a\x19.pb.ResetPasswordResponse\"U\x92A5\x12\x0eReset Password\x1a#Use this API to reset the password.\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/reset_passwordB\x86\x01\x92A]\x12[\n" +
	"\x14Money Management API\">\n" +
	"\x05gufir\x12\x18https://github.com/gufir\x1a\x1bgunawan.firdaus99@ymail.com2\x032.0Z$github.com/gufir/money-management/pbb\x06proto3"

var file_service_money_management_proto_goTypes = []any{
	(*CreateUserRequest)(nil),              // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),              // 1: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),               // 2: pb.LoginUserRequest
	(*CreateTransactionRequest)(nil),       // 3: pb.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),       // 4: pb.UpdateTransactionRequest
	(*CreateCategoriesRequest)(nil),        // 5: pb.CreateCategoriesRequest
	(*UpdateCategoriesRequest)(nil),        // 6: pb.UpdateCategoriesRequest
	(*GetCategoriesRequest)(nil),           // 7: pb.GetCategoriesRequest
	(*GetTransactionRequest)(nil),          // 8: pb.GetTransactionRequest
	(*GetUserRequest)(nil),                 // 9: pb.GetUserRequest
	(*CreateReportRequest)(nil),            // 10: pb.CreateReportRequest
	(*CreateMonthlyReportRequest)(nil),     // 11: pb.CreateMonthlyReportRequest
	(*GetReportByUserRequest)(nil),         // 12: pb.GetReportByUserRequest
	(*GetDetailsReportByUserRequest)(nil),  // 13: pb.GetDetailsReportByUserRequest
	(*GetReportByDateRequest)(nil),         // 14: pb.GetReportByDateRequest
	(*GetReportByCategoryRequest)(nil),     // 15: pb.GetReportByCategoryRequest
	(*VerifyEmailRequest)(nil),             // 16: pb.VerifyEmailRequest
	(*ForgotPasswordRequest)(nil),          // 17: pb.ForgotPasswordRequest
	(*ResetPasswordRequest)(nil),           // 18: pb.ResetPasswordRequest
	(*CreateUserResponse)(nil),             // 19: pb.CreateUserResponse
	(*UpdateUserResponse)(nil),             // 20: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),              // 21: pb.LoginUserResponse
	(*CreateTransactionResponse)(nil),      // 22: pb.CreateTransactionResponse
	(*UpdateTransactionResponse)(nil),      // 23: pb.UpdateTransactionResponse
	(*CreateCategoriesResponse)(nil),       // 24: pb.CreateCategoriesResponse
	(*UpdateCategoriesResponse)(nil),       // 25: pb.UpdateCategoriesResponse
	(*GetCategoriesResponse)(nil),          // 26: pb.GetCategoriesResponse
	(*GetTransactionResponse)(nil),         // 27: pb.GetTransactionResponse
	(*GetUserResponse)(nil),                // 28: pb.GetUserResponse
	(*CreateReportResponse)(nil),           // 29: pb.CreateReportResponse
	(*CreateMonthlyReportResponse)(nil),    // 30: pb.CreateMonthlyReportResponse
	(*GetReportByUserResponse)(nil),        // 31: pb.GetReportByUserResponse
	(*GetDetailsReportByUserResponse)(nil), // 32: pb.GetDetailsReportByUserResponse
	(*GetReportByDateResponse)(nil),        // 33: pb.GetReportByDateResponse
	(*GetReportByCategoryResponse)(nil),    // 34: pb.GetReportByCategoryResponse
	(*VerifyEmailResponse)(nil),            // 35: pb.VerifyEmailResponse
	(*ForgotPasswordResponse)(nil),         // 36: pb.ForgotPasswordResponse
	(*ResetPasswordResponse)(nil),          // 37: pb.ResetPasswordResponse
}
var file_service_money_management_proto_depIdxs = []int32{
	0,  // 0: pb.MoneyManagement.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.MoneyManagement.UpdateUser:input_type -> pb.UpdateUserRequest
	2,  // 2: pb.MoneyManagement.LoginUser:input_type -> pb.LoginUserRequest
	3,  // 3: pb.MoneyManagement.CreateTransaction:input_type -> pb.CreateTransactionRequest
	4,  // 4: pb.MoneyManagement.UpdateTransaction:input_type -> pb.UpdateTransactionRequest
	5,  // 5: pb.MoneyManagement.CreateCategories:input_type -> pb.CreateCategoriesRequest
	6,  // 6: pb.MoneyManagement.UpdateCategories:input_type -> pb.UpdateCategoriesRequest
	7,  // 7: pb.MoneyManagement.GetCategories:input_type -> pb.GetCategoriesRequest
	8,  // 8: pb.MoneyManagement.GetTransaction:input_type -> pb.GetTransactionRequest
	9,  // 9: pb.MoneyManagement.GetUser:input_type -> pb.GetUserRequest
	10, // 10: pb.MoneyManagement.CreateReport:input_type -> pb.CreateReportRequest
	11, // 11: pb.MoneyManagement.CreateMonthlyReport:input_type -> pb.CreateMonthlyReportRequest
	12, // 12: pb.MoneyManagement.GetReportByUser:input_type -> pb.GetReportByUserRequest
	13, // 13: pb.MoneyManagement.GetDetailsReportByUser:input_type -> pb.GetDetailsReportByUserRequest
	14, // 14: pb.MoneyManagement.GetReportByDate:input_type -> pb.GetReportByDateRequest
	15, // 15: pb.MoneyManagement.GetReportByCategory:input_type -> pb.GetReportByCategoryRequest
	16, // 16: pb.MoneyManagement.VerifyEmail:input_type -> pb.VerifyEmailRequest
	17, // 17: pb.MoneyManagement.ForgotPassword:input_type -> pb.ForgotPasswordRequest
	18, // 18: pb.MoneyManagement.ResetPassword:input_type -> pb.ResetPasswordRequest
	19, // 19: pb.MoneyManagement.CreateUser:output_type -> pb.CreateUserResponse
	20, // 20: pb.MoneyManagement.UpdateUser:output_type -> pb.UpdateUserResponse
	21, // 21: pb.MoneyManagement.LoginUser:output_type -> pb.LoginUserResponse
	22, // 22: pb.MoneyManagement.CreateTransaction:output_type -> pb.CreateTransactionResponse
	23, // 23: pb.MoneyManagement.UpdateTransaction:output_type -> pb.UpdateTransactionResponse
	24, // 24: pb.MoneyManagement.CreateCategories:output_type -> pb.CreateCategoriesResponse
	25, // 25: pb.MoneyManagement.UpdateCategories:output_type -> pb.UpdateCategoriesResponse
	26, // 26: pb.MoneyManagement.GetCategories:output_type -> pb.GetCategoriesResponse
	27, // 27: pb.MoneyManagement.GetTransaction:output_type -> pb.GetTransactionResponse
	28, // 28: pb.MoneyManagement.GetUser:output_type -> pb.GetUserResponse
	29, // 29: pb.MoneyManagement.CreateReport:output_type -> pb.CreateReportResponse
	30, // 30: pb.MoneyManagement.CreateMonthlyReport:output_type -> pb.CreateMonthlyReportResponse
	31, // 31: pb.MoneyManagement.GetReportByUser:output_type -> pb.GetReportByUserResponse
	32, // 32: pb.MoneyManagement.GetDetailsReportByUser:output_type -> pb.GetDetailsReportByUserResponse
	33, // 33: pb.MoneyManagement.GetReportByDate:output_type -> pb.GetReportByDateResponse
	34, // 34: pb.MoneyManagement.GetReportByCategory:output_type -> pb.GetReportByCategoryResponse
	35, // 35: pb.MoneyManagement.VerifyEmail:output_type -> pb.VerifyEmailResponse
	36, // 36: pb.MoneyManagement.ForgotPassword:output_type -> pb.ForgotPasswordResponse
	37, // 37: pb.MoneyManagement.ResetPassword:output_type -> pb.ResetPasswordResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_money_management_proto_init() }
func file_service_money_management_proto_init() {
	if File_service_money_management_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_create_transaction_proto_init()
	file_rpc_update_transaction_proto_init()
	file_rpc_create_categories_proto_init()
	file_rpc_update_categories_proto_init()
	file_rpc_get_categories_proto_init()
	file_rpc_get_transaction_proto_init()
	file_rpc_get_user_proto_init()
	file_rpc_create_report_proto_init()
	file_rpc_create_monthly_report_proto_init()
	file_rpc_get_report_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_forgot_password_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_money_management_proto_rawDesc), len(file_service_money_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_money_management_proto_goTypes,
		DependencyIndexes: file_service_money_management_proto_depIdxs,
	}.Build()
	File_service_money_management_proto = out.File
	file_service_money_management_proto_goTypes = nil
	file_service_money_management_proto_depIdxs = nil
}
